### ISSUE TITLE
Speed up response

### ISSUE THREAD

**Issue by ygzgxyz** [spoqa/slack-translator#13]
In case of late response, slack shows timeout warning to user who invoked the command and it's quiet annoying.

I guess we can remove those warnings by posting translated message lazily in async

**Comment by jckdotim** [comment]
Recently, Slack shows the timeout warning text. Heroku requires paid plan for background worker so that I'll make this async feature as an option.

**Comment by ygzgxyz** [comment]
cool, awesome. Thank you so much!
